name: Build WinArk

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.png"
      - "License"
      - "/doc/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.png"
      - "License"
      - "/doc/**"
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Install WDK
      run: |
        nuget install Microsoft.Windows.DriverKit -Version 10.0.22000.1

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install WTL and WIL
      run: |
        .\vcpkg\vcpkg.exe install wil:x64-windows
        nuget install wtl -Version 10.0.10320
    
    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg.exe install capstone[x86]:x86-windows-static
        .\vcpkg\vcpkg.exe install capstone[x86]:x64-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x86-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x64-windows-static

    - name: install Zydis kernel library
      run: |
        .\vcpkg\vcpkg.exe install zydis

    - name: Compile Anti-Rootkit driver
      run: |
        msbuild ./Anti-Rootkit.sln /p:Configuration=Release

    - name: Compile WinArk
      run: |
        cd WinArk
        msbuild ./WinArk.sln /p:Configuration=Release /p:Platform=x64
