name: Build WinArk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg.exe install capstone[x86]:x86-windows-static
        .\vcpkg\vcpkg.exe install capstone[x86]:x64-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x86-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x64-windows-static

    - name: Compile Zydis kernel library
      run: |
        cd path/to/Zydis
        msbuild Zydis.sln /p:Configuration=Release /p:Platform=Win32
        msbuild Zydis.sln /p:Configuration=Release /p:Platform=x64

    - name: Compile Anti-Rootkit driver
      run: |
        msbuild path/to/Anti-Rootkit.sln /p:Configuration=Release

    - name: Compile WinArk
      run: |
        msbuild path/to/WinArk.sln /p:Configuration=Release
